import Link from "next/link";

export const metadata = {
  title: "Privacy Policy | AOPay",
  description:
    "Read AOPay Privacy Policy to understand how we collect, use, and protect your personal information when using our Solutions.",
  robots: "index, follow",
  viewport: "width=device-width, initial-scale=1",

  openGraph: {
    title: "Privacy Policy | AOPay",
    description:
      "Read AOPay Privacy Policy to understand how we collect, use, and protect your personal information when using our Solutions.",
    url: "https://aopay.in/privacy-policy",
    siteName: "AOPay Privacy Policy",
    type: "website",
    images: [
      {
        url: "https://aopay.in/images/privacy_policy_og.jpg", // replace with actual image
        width: 1200,
        height: 630,
        alt: "AOPay Privacy Policy",
      },
    ],
  },
  alternates: {
    canonical: "https://aopay.in/privacy-policy",
  },
};
  
const Privacy = () => {
  return (
    <div className="bg-white py-24">
      <div className="container mx-auto px-6">
        <header className="text-center mb-10">
          <h1 className="text-4xl font-bold text-gradient">
            How We Protect Your Information – Privacy Policy
          </h1>
          {/* <p className="mt-4 text-gray-600">Effective Date: January 6, 2025</p> */}
        </header>

        <section className="mb-10">
          <h2 className="text-2xl font-semibold text-gray-800">Introduction</h2>
          <p className="mt-4 text-gray-600 leading-relaxed">
            This document is an electronic record in terms of the Information
            Technology Act, 2000, and the applicable rules made thereunder,
            along with the relevant provisions of other statutes as amended by
            the Information Technology Act, 2000. This electronic record is
            generated by a computer system and does not require any physical or
            digital signature to be valid or binding. AOPAY, a company
            incorporated under the Companies Act, 1956, having its registered
            office at Building No. 73, Block B-1, Sewak Park Extension, Near
            NSUT, Uttam Nagar, New Delhi - 110059, (hereinafter referred to as
            “AOPAY”, “we”, “us”, or “our”) owns and operates the website{" "}
            <Link
              href="https://www.aopay.in"
              className="underline text-blue-500"
            >
              www.aopay.in
            </Link>{" "}
            (“Website” or “Platform”). At AOPAY, we value your privacy and are
            committed to protecting your personal information. This Privacy
            Policy explains how we collect, use, disclose, and safeguard your
            information when you visit or use our Platform. By accessing or
            registering on the Platform, you acknowledge that you have read,
            understood, and agreed to the terms of this Privacy Policy. You also
            expressly consent to our use and disclosure of your personal
            information in accordance with this Policy and confirm that any
            information provided by you is given under a lawful contract. You
            further authorize AOPAY, its employees, and its partners to contact
            you via phone, SMS, or email as necessary. This Privacy Policy is
            subject to change at any time without prior notice. We encourage you
            to review it periodically to stay informed of any updates. The most
            current version of the policy will always be available at:{" "}
            <Link
              href="https://www.aopay.in/privacy-policy"
              className="underline text-blue-500"
              target="_blank"
              rel="noopener noreferrer"
            >
              {" "}
              www.aopay.in/privacy-policy
            </Link>
            .
          </p>
        </section>

        <section className="mb-10">
          <h2 className="text-2xl font-semibold text-gray-800">Your Privacy</h2>
          <p className="mt-4 text-gray-600 leading-relaxed">
            At AOPAY, we are committed to protecting your privacy. We value your
            trust in us and work hard to earn your confidence so that you can
            enjoy our services and recommend them to others. Please read the
            following policy to understand how your personal information will be
            treated as you use our Website. For this Privacy Policy, "users"
            (also referred to as "you," "your," and "user") shall mean all
            persons having access to the Platform of AOPAY and/or persons
            availing services offered through the Platform or otherwise,
            including without limitation AOPAY's service providers, end
            customers, and/or any third party using or accessing the AOPAY
            Platform/Website.
          </p>
        </section>

        <section className="mb-10">
          <h2 className="text-2xl font-semibold text-gray-800">
            Privacy Assurance
          </h2>
          <p className="mt-4 text-gray-600 leading-relaxed">
            We promise that we will not sell or rent your personal information
            to third parties or use the same for unsolicited emails or messages
            without your explicit consent. From time to time, we may reveal
            general statistical information about our Platform/Website and
            visitors, such as the number of visitors, services purchased, etc.
            Your trust and confidence are our highest priority.
          </p>
        </section>

        <section className="mb-10">
          <h2 className="text-2xl font-semibold text-gray-800">
            Information Collected
          </h2>
          <p className="mt-4 text-gray-600 leading-relaxed">
            When you use our Platform/Website or services offered through the
            Platform/Website, we collect and store your personal information to
            record, support, and facilitate your participation in the services.
            We collect this information primarily to provide the services you
            request. It is also used for the initial service provision and
            ongoing user support. The informationcan be used by AOPAY for
            sending periodic emails announcing important service changes, new
            features, technical updates, and other news. You may choose to
            unsubscribe from these emails by replying with "Unsubscribe" in the
            subject. The information is also used to improve the efficiency and
            effectiveness of the Platform/Website.
          </p>
        </section>

        <section className="mb-10">
          <h2 className="text-2xl font-semibold text-gray-800">
            Types of Information Collected
          </h2>
          <ul className="list-disc ml-6 mt-4 text-gray-600">
            <li>
              <strong>Personal Information: </strong>This may include name,
              mailing address, phone number, email address, and other
              information required to provide services requested by the user.
              This information is voluntarily provided by the user through
              various forms, emails, phone interactions, and/or e-KYC
              procedures.
            </li>
            <li>
              <strong>Non-Personal Information </strong>This may include
              referral URLs, IP addresses, browser details, and other
              non-personally identifiable data collected through cookies. These
              cookies help us identify users and improve their experience. You
              can choose to reject cookies by modifying your browser settings.
            </li>
          </ul>
        </section>

        <section className="mb-10">
          <h2 className="text-2xl font-semibold text-gray-800">
            How We Use Your Information
          </h2>
          <p className="mt-4 text-gray-600 leading-relaxed">
            We use your personal information to facilitate the services you
            request. We do not sell, rent, or trade any personally identifiable
            information of our users. We may share your collected information
            with our affiliates and service providers under contract (such as
            customer support and data analytics) to support the operation of the
            Platform/Website and our services.
          </p>
          <h4 className="text-lg font-semibold text-gray-800">
            We may use your personal information to:
          </h4>
          <ul className="list-disc ml-6 mt-4 text-gray-600">
            <li>Resolve disputes</li>
            <li>Troubleshoot problems</li>
            <li>Promote safe transactions</li>
            <li>Collect fees owed</li>
            <li>Measure user interest in the services provided by us.</li>
            <li>Customize your experience</li>
            <li>
              Detect and protect us from errors, fraud, and other criminal
              activities.
            </li>
            <li>
              Inform you about updates to our online and offline services.
            </li>
          </ul>
          <h3 className="mt-4 text-gray-600 leading-relaxed">
            We may also use your personal information to display targeted
            content and services. By accepting this Privacy Policy, you
            expressly agree to receive such information. If you do not wish to
            receive these communications, you can opt out by clicking
            unsubscribe on any email communication or writing to us.
          </h3>
        </section>

        <section className="mb-10">
          <h2 className="text-2xl font-semibold text-gray-800">
            Disclosure of information
          </h2>
          <h3 className="mt-4 text-gray-600 leading-relaxed">
            Your personal information is an important part of our business, and
            we are not in the business of selling it to others. We only share
            information under the following circumstances:
          </h3>
          <ul className="list-disc ml-6 mt-4 text-gray-600">
            <li>Disclosure to third parties with your prior permission.</li>
            <li>
              Disclosure as required by law or to comply with legal
              requirements.
            </li>
          </ul>
          <h3 className="mt-4 text-gray-600 leading-relaxed">
            We may use your information for new, unanticipated uses not
            previously disclosed in our Privacy Policy. If our information
            practices change in the future, we will contact you and provide the
            ability to opt out of these new uses. We may provide visitors with
            access to all information they have provided to us, upon request.
          </h3>
        </section>

        <section className="mb-10">
          <h2 className="text-2xl font-semibold text-gray-800">
            Data Retention & Deletion
          </h2>
          <h3 className="mt-4 text-gray-600 leading-relaxed">
            AOPAY may store your personal information (including sensitive
            personal information) for a period as required under applicable laws
            in India. After the retention period, we will delete your
            information in compliance with applicable regulations.
          </h3>
        </section>

        <section className="mb-10">
          <h2 className="text-2xl font-semibold text-gray-800">Security</h2>
          <h3 className="mt-4 text-gray-600 leading-relaxed">
            To protect your privacy and security, we use industry-standard
            encryption technologies when transferring and receiving user data
            exchanged with our site. We comply with the security standards under
            the Information Technology Act, 2000, and the Information Technology
            (Reasonable Security Practices and Procedures for Protection of
            Sensitive Personal Data and Information) Rules, 2011.
          </h3>
        </section>

        <section className="mb-10">
          <h2 className="text-2xl font-semibold text-gray-800">
            Advertisements on Website
          </h2>
          <h3 className="mt-4 text-gray-600 leading-relaxed">
            We use third-party advertising companies to serve ads when you visit
            our Website. These companies may use your information (excluding
            your name, address, email address, or telephone number) to provide
            advertisements about services of interest to you. We do not control
            the privacy practices of these advertisers, so we encourage you to
            evaluate their privacy policies before providing any information.
          </h3>
        </section>

        <section className="mb-10">
          <h2 className="text-2xl font-semibold text-gray-800">
            Links to Other Sites
          </h2>
          <h3 className="mt-4 text-gray-600 leading-relaxed">
            Our Website may contain links to other websites that may collect
            personally identifiable information about you. Please be aware that
            AOPAY is not responsible for the privacy practices or the content of
            those linked websites.
          </h3>
        </section>

        <section className="mb-10">
          <h2 className="text-2xl font-semibold text-gray-800">Amendments</h2>
          <h3 className="mt-4 text-gray-600 leading-relaxed">
            AOPAY reserves the right to revise its policies at any time without
            prior notice.
          </h3>
        </section>

        <section className="mb-10">
          <h2 className="text-2xl font-semibold text-gray-800">
            Contact Information
          </h2>
          <h3 className="mt-4 text-gray-600 leading-relaxed">
            If you have any questions or concerns regarding this Privacy Policy,
            or if you wish to exercise your rights regarding your data, you may
            contact us at:
          </h3>
          <h4 className="text-lg font-semibold text-gray-800 mt-4">Nodal Desk</h4>
          <p className="mt-2 text-gray-600 leading-relaxed">AOPAY</p>
          <ul className="list-disc ml-6 mt-4 text-gray-600">
            <li>
              <strong>Address: </strong>Building No. 73, Block B-1, Sewak Park
              Extension, Near NSUT, Uttam Nagar, New Delhi - 110059
            </li>
            <li>
              <strong>Email: </strong>info@aopay.in
            </li>
          </ul>
          <p className="mt-4 text-gray-600 leading-relaxed">
            By using our Platform/Website, you acknowledge and agree to the
            terms of this Privacy Policy.
          </p>
        </section>
      </div>
    </div>
  );
};

export default Privacy;
