"use client";

import { motion } from "framer-motion";

export default function NBFCOperationalWorkflows() {
  const workflowCards = [
    {
      title: "Fintech Company Responsibilities",
      points: [
        "Technology Platform: Provide advanced technical infrastructure for loan origination, processing, and management.",
        "Capital Infusion: Supply funding deposited with fund managers as FLDG, later transferred to NBFCs as intercorporate deposits.",
        "Lead Generation: Source quality borrower leads through marketing campaigns and customer acquisition channels.",
        "Risk Tools: Share FLDG guarantees and risk assessment software for informed lending decisions.",
        "Marketing Support: Run campaigns to increase NBFC business visibility and customer reach.",
        "Collection Services: Offer debt collection assistance to NBFCs for loan recovery.",
      ],
    },
    {
      title: "NBFC Operational Role",
      points: [
        "Loan Processing: Process and disburse loans to leads generated by fintech partners.",
        "Risk Assessment: Utilize fintech-provided data and tools to minimize lending risks.",
        "Regulatory Compliance: Maintain RBI compliance, reporting, and governance standards.",
        "Profit Sharing: Distribute agreed revenue percentages with collaborating fintechs.",
        "Risk Retention: Keep designated percentage of profit as compensation for risk services.",
        "Portfolio Management: Monitor loan performance, NPAs, and collection efficiency.",
      ],
    },
    {
      title: "Intermediary Legal Firm Functions",
      points: [
        "Fund management per collaboration agreement terms.",
        "Escrow account oversight and reconciliation.",
        "Compliance monitoring and audit support.",
        "Dispute resolution facilitation.",
        "Service fee collection from collaborators.",
      ],
    },
  ];

  const complianceCards = [
    {
      title: "Compliance Requirements for NBFCs",
      points: [
        "Document Verification: Implement online verification services for all borrower documents with secure storage.",
        "Data Retention: Maintain borrower profile storage capacity for minimum 5 years as per RBI norms.",
        "Loan Processing Services: Provide complete loan execution including photo capture, e-stamp duty payment, and documentation.",
        "Credit Bureau Reporting: Report loan inquiries, disbursements, delays, and defaults to Credit Information Companies (CIBIL, Experian, Equifax, CRIF).",
        "Regulatory Adherence: Follow all RBI compliance norms including KYC, AML, fair practices code.",
        "Audit Requirements: Appoint Chartered Accountants for auditing collaborating fintechs for risk assessment purposes.",
        "NPA Classification: Follow 45/90-day norm for identifying and provisioning non-performing assets.",
      ],
    },
    {
      title: "Compliance Requirements for Fintechs",
      points: [
        "Lending Limits: Fintechs can extend loans or guarantees up to 100% of free reserves OR 60% of paid-up capital, whichever is higher.",
        "GST Obligations: Pay GST on loan processing fees and related charges as per applicable tax slabs.",
        "ECB Compliance: Foreign fintechs must follow External Commercial Borrowing guidelines when raising funds for Indian operations.",
        "Data Localization: Maintain servers in India and ensure data protection per Indian regulations.",
        "RBI Reporting: Submit periodic reports on lending activities, NPAs, and FLDG utilization.",
      ],
    },
    {
      title: "Technology Requirements for Fintech Partners",
      points: [
        "Loan Origination System (LOS): Comprehensive platform for end-to-end loan origination and processing.",
        "Loan Management System (LMS): Robust system for monitoring, tracking, and managing active loans.",
        "Collection System: Automated collection tools preferably integrated into mobile apps for borrower convenience.",
        "Underwriting Software: Advanced credit assessment and underwriting algorithms owned by fintech.",
        "Data Security Infrastructure: Enterprise-grade IT infrastructure ensuring secure transfer of user data and loan processing information.",
        "Document Integration: Ability to integrate various ID documents (Aadhaar, PAN, Voter ID, Driving License) for verification.",
        "Bank Statement Analyzer: Software capable of analyzing bank statements for income verification and cash flow assessment.",
        "Employment Verification System: Automated verification for employment status and employer details.",
        "Server Localization: Application servers must be located in India with data protection measures complying with Indian law.",
      ],
    },
  ];

  return (
    <section className="max-w-6xl mx-auto px-6 py-16 bg-gray-50">
      {/* Section 1: Operational Workflows */}
      <div className="text-center mb-12">
        <motion.h2
          initial={{ opacity: 0, y: 15 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          viewport={{ once: true }}
          className="text-3xl md:text-4xl font-bold text-gray-900"
        >
          Operational Workflows in NBFC Collaboration
        </motion.h2>
        <p className="text-gray-600 mt-4 max-w-3xl mx-auto">
          Understanding how each party contributes to the collaboration
          ecosystem ensures smooth operations and clear accountability.
        </p>
      </div>

      <div className="grid md:grid-cols-3 gap-8 mb-20">
        {workflowCards.map((card, i) => (
          <motion.div
            key={i}
            initial={{ opacity: 0, y: 10 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.4, delay: i * 0.1 }}
            viewport={{ once: true }}
            className="bg-white border border-gray-200 rounded-2xl p-6 shadow-sm hover:shadow-lg transition"
          >
            <h3 className="text-xl font-semibold text-gray-900 mb-4">
              {card.title}
            </h3>
            <ul className="list-disc pl-5 space-y-2 text-gray-700 text-sm">
              {card.points.map((point, idx) => (
                <li key={idx}>{point}</li>
              ))}
            </ul>
          </motion.div>
        ))}
      </div>

      {/* Section 2: Compliance Requirements */}
      <div className="text-center mb-12">
        <motion.h2
          initial={{ opacity: 0, y: 15 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          viewport={{ once: true }}
          className="text-3xl md:text-4xl font-bold text-gray-900"
        >
          Comprehensive Document and Compliance Requirements
        </motion.h2>
        <p className="text-gray-600 mt-4 max-w-3xl mx-auto">
          Successful NBFC collaboration demands adherence to specific compliance
          frameworks for both NBFCs and fintechs. Here's what each party must
          maintain:
        </p>
      </div>

      <div className="grid md:grid-cols-3 gap-8">
        {complianceCards.map((card, i) => (
          <motion.div
            key={i}
            initial={{ opacity: 0, y: 10 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.4, delay: i * 0.1 }}
            viewport={{ once: true }}
            className="bg-white border border-gray-200 rounded-2xl p-6 shadow-sm hover:shadow-lg transition"
          >
            <h3 className="text-xl font-semibold text-gray-900 mb-4">
              {card.title}
            </h3>
            <ul className="list-disc pl-5 space-y-2 text-gray-700 text-sm">
              {card.points.map((point, idx) => (
                <li key={idx}>{point}</li>
              ))}
            </ul>
          </motion.div>
        ))}
      </div>
    </section>
  );
}
